name: Auto compile with openwrt sdk v1

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      upload-artifacts:
        description: "Upload compiled image to Artifacts only"
        required: false
        default: false
        type: boolean
      upload-prerelease:
        description: "Upload as pre-release"
        required: false
        default: false
        type: boolean

env:
  TZ: Asia/Jakarta

jobs:
  job_build_rta:
    name: Build RTA (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PKG_VERSION from Makefile
        id: vars
        run: echo "::set-output name=version::$(grep 'PKG_VERSION:=' Makefile | cut -d '=' -f2)"

      - name: Reading Package 
        id: list_package
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: main
          path: list_packages.txt

      - name: Install packages
        run: |
          echo "Install packages"
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev git-core subversion gettext unzip zlib1g-dev file perl libssl-dev wget

      - name: Initialization environment
        env:
          url_sdk: https://archive.openwrt.org/releases/21.02.5/targets/x86/64/openwrt-sdk-21.02.5-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        run: |
          wget ${{ env.url_sdk }}
          file_name=$(echo ${{env.url_sdk}} | awk -F/ '{print $NF}')
          mkdir sdk && tar -xJf $file_name -C ./sdk --strip-components=1
          cd sdk  
          echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-21.02" > feeds.conf
          echo "src-git-full packages https://github.com/openwrt/packages.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full luci https://git.openwrt.org/project/luci.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-21.02"  >> feeds.conf
          git clone https://github.com/${{ github.repository }}.git package/downloads/luci-app-rakitiw
          ./scripts/feeds update -a
          for package in ${{ steps.list_package.outputs.content}}; do
            ./scripts/feeds install -d n "$package"
          done

      - name: Configure RTA (main)
        run: |
          cd sdk
          for package in ${{ steps.list_package.outputs.content}}; do
            ./scripts/feeds install "$package"
          done
          make defconfig

      - name: Compile RTA (main)
        id: compile
        run: |
          cd sdk
          for package in ${{ steps.list_package.outputs.content}}; do
            make "package/$package/compile"
          done
          mv bin/packages/x86_64/base/ ../
          cd ..
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y.%m.%d-%H:%M:%S')" >> $GITHUB_ENV

      - name: Upload All Firmware to Artifacts
        if: github.event.inputs.upload-artifacts == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt RTA Packages
          path: ${{ env.FIRMWARE }}/base/*.ipk

      - name: Upload Firmware to Release
        uses: svenstaro/upload-release-action@v2
        if: github.event.inputs.upload-artifacts == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.FIRMWARE }}/base/*.ipk
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: "${{ steps.vars.outputs.version }}"
          release_name: "Luci App Rakitiw Version - ${{ steps.vars.outputs.version }} - ${{ env.DATETIME }}"
          overwrite: true
          prerelease: ${{ inputs.upload-prerelease }}
          body: |
            Build date: ${{ env.DATETIME }} For Version : ${{ steps.vars.outputs.version }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
